### ISSUE TITLE
Outdated PyPi release

### ISSUE THREAD

**Issue by mheppner** [torchbox/wagtailguide#17]
The current version on PyPi is 1.0.5, but it's missing some recent fixes (mainly #8 and #9). Any chance to get a new version pushed?

**Comment by kevinhowbrook** [comment]
Thanks @mheppner 

I've added https://github.com/kevinhowbrook/wagtailguide/pull/18 if you'd like to review it?

**Comment by kevinhowbrook** [comment]
Thanks @mheppner, updated version is published https://pypi.org/project/wagtail-guide/
