### ISSUE TITLE
Add option to remove from menu

### ISSUE THREAD

**Issue by tomdyson** [torchbox/wagtailguide#22]
Now Wagtail has its own [help menu](https://docs.wagtail.org/en/stable/releases/4.1.html#what-s-new-dashboard-banner-and-help-menu) which includes a link to the generic [Wagtail Guide](https://guide.wagtail.org/), it could be confusing to have this site-specific guide elsewhere in the menu. Could we have an option to remove this guide from the menu, and instructions for including it within the new help menu (using the [register-help-menu-item](https://docs.wagtail.org/en/stable/reference/hooks.html#register-help-menu-item) hook).

![screenshot 2022-11-30 at 10 04 00](https://user-images.githubusercontent.com/15543/204767180-f9156883-f71b-48c9-9792-3e4db9334106.png)

**Comment by kevinhowbrook** [comment]
Thanks @tomdyson, makes sense that.

I guess we are talking about an overall settings option that will do the following:

- Turn off/Hide the core Help > Editor guide menu item
- Move the wagtailguide 'Editor guide' menu item into the help menu, So it's replacing it.

Might be worth adding a setting for the wagtailguide menu label, should someone want both of these, they could name the wagtailguide one 'CMS Guide' or 'Publishers Guide'

I'll have a look into this :+1:

**Comment by kevinhowbrook** [comment]
I've hashed something together here https://github.com/kevinhowbrook/wagtailguide/pull/23
It's basically v2.0.0 because I've dropped support for older versions, I'll let the older PyPI releases offer that
