### ISSUE TITLE
RichTextBlock doesn't show up.

### ISSUE THREAD

**Issue by KalobTaulien** [torchbox/wagtailguide#5]
Hey Kevin,

Awesome plugin! I'm just tinkering around with it right now and I'm really liking it! 

One thing I noticed when adding StreamFields (editing) was the RichTextBlock didn't show up for me. I'm using a base Wagtail installation using v2.5.1. I've also cloned this repo into an existing project instead of using pip. When I tried `pip install ...` it worked. 

Here's a screenshot
![image](https://user-images.githubusercontent.com/4743971/58751290-f93d2300-8459-11e9-8141-20283c58f874.png)

If this is a non-issue feel free to close this ticket. 

Again, great job on this plugin!

**Comment by kevinhowbrook** [comment]
Hey @KalobTaulien, thanks, I'm glad you find it useful. I'm a big fan of your tutorials :) 

I'm trying to recreate this locally with 2.5.1 but I cannot seem to. It looks like a JS error is stopping draftail loading though. Could you check your console to see if that's the case?

Cheers

**Comment by KalobTaulien** [comment]
Hey @kevinhowbrook 

I must have had some caching issue because there weren't any console errors. I just slammed on the hard fresh button a few times and it fixed again. 

This issue was a non-issue! 

Cheers!
